### ISSUE TITLE
[FEAT]: API Endpoint for  retrieving the profile data of the currently authenticated user

### ISSUE THREAD

**Issue by SamixYasuke** [hngprojects/hng_boilerplate_expressjs#120]
### Description

Implement an endpoint to retrieve the profile data of the currently authenticated user. This will allow users to access their own profile information.

### Endpoint Feature
- This Endpoint allows users to retrieve their profile data.
- It Ensures that the requester is authenticated before the request is made.

### Acceptance Criteria

- [ ] The endpoint should be accessible at `GET /api/v1/users/me`
- [ ] The endpoint should return a 200 OK status code with the appropriate message in the response body.
- [ ] The responses should be in camel case.

- **Request Example**:

  ```http
  GET /api/v1/users/me HTTP/1.1
  Authorization: Bearer <token>
  ```

- **Response Example**:
  ```json
  {
    "status_code": 200,
    "data": {
      "id": "596406f3-b596-4176-ac32-a0328dfdb8b5",
      "user_name": "Samixx Yasuke",
      "email": "samueladekolu4@gmail.com",
      "profile_picture": "https://example/profile-pictures/samixx.jpg",
      "bio": "Developer at HNG Tech"
    }
  }
  ```

### Data Validation

- Ensure the token is valid and the user exists.
- Validate that the user is authenticated.

### Authentication and Authorization

- Only authenticated users can access this endpoint.
- The `Authorization` header must contain a valid JWT token.

### Error Handling

- **Error Responses**:
  - `401 Unauthorized` if the token is missing or invalid.
  - `404 Not Found` if the user does not exist.
  - `500 Internal Server Error` if unexpected server error occurs.

### Performance and Security

- **Performance Considerations**:
  - Optimize the query to retrieve user data.
- **Security Concerns**:
  - Ensure sensitive data is not exposed when returning user data (e.g password).
  - Validate and sanitize all inputs (e.g user id must be uuid i.e. if uuid is used as the user id).

### Documentation

- **API Documentation**:
  - Document the endpoint in the API documentation with request and response examples using the standard OpenAPI 3.1.0 standard.
- **Technical Notes**:
  - Include details on the authentication mechanism.

### Testing Requirements

- **Unit Tests**:
  - Write tests to cover the successful retrieval of user data.
  - Write tests for all error cases.

### Dependencies and Impact

- **Dependencies**:
  - Ensure the user authentication service is up and running.
  - Ensure the auth middleware is active.

**Comment by AdeGneus** [comment]
1. You are asked to get a user profile (dashboard) and an endpoint was suggested for you, that is, `/me`. Only the admin should use the `/api/v1/users/:user-id` to get a single user.
2. The endpoint should follow the REST API resource naming convention i.e `/api/v1/users`
3. The feature should be about what you want to implement and not HTTP method and route

I stopped commenting here because it's clear that you didn't follow the guide we shared

**Comment by SamixYasuke** [comment]
The correction has been effected.

**Comment by AdeGneus** [comment]
We are using snake case for the responses

**Comment by SamixYasuke** [comment]
Fixed @AdeGneus
