### ISSUE TITLE
[FEAT]: API Endpoint To Allow Users to Create a Blog Post

### ISSUE THREAD

**Issue by StarmannRassy** [hngprojects/hng_boilerplate_expressjs#123]
### **Description**
Implement an API endpoint for creating blog posts. This endpoint allows authenticated users to create blog posts with a title and content.

### **Endpoint Feature**
This endpoint enables authenticated users to create blog posts.
Limited to submitting posts with a valid title and content.

### **Acceptance Criteria**

- [ ] The endpoint should be accessible at POST /api/v1/blog/create.

- [ ] The endpoint should accept HTTP POST requests.

- [ ] The endpoint should create a blog post with the provided title and content.

- [ ] The endpoint should return a 200 OK status code with a success message in the response body.

**POST** /api/v1/blog/create
**Content-Type:** application/json
```json
{
  "title": "My First Blog Post",
  "content": "This is the content of my first blog post."
}
```

On successful creation of the blog post, the API should return a 200 OK status code. The response body should contain a success message:
```json
{
  "status": "success",
  "status_code": 200,
  "message": "Blog post created successfully."
}
```

### **Blog Post Model:**

Create a new model for blog posts with the following fields:

- ```title ```(String, required)
- ```content``` (Text, required)
- ```author_id``` (Integer, foreign key to the User model)
- ```created_at``` (Date, default to current timestamp)
- ```updated_at``` (Date, default to current timestamp)

### **Data Validation**

**Input Validation:**

Confirm that title and content are provided and valid.
```Example:``` If title or content is invalid or missing, return a 400 status code with an error message.
```json
{
  "status": "unsuccessful",
  "status_code": 400,
  "message": "Valid title and content must be provided."
}
```

**Output Validation:**

Ensure the response format is correct and includes appropriate status codes and messages.
If there is an error in creating the blog post (e.g., database issues), the API should return a 500 Internal Server Error status code with an appropriate message:
```json
{
  "status": "unsuccessful",
  "status_code": 500,
  "message": "Failed to create blog post. Please try again later."
}
```

### **Authentication and Authorization**

**Authentication:**

Verify that the user is authenticated before allowing access to the endpoint.
```Example:``` Use middleware to check for a valid authentication token.

**Authorization:**

- Ensure that only authorized users can create blog posts.
- Implement authorization using middleware to check the user’s roles and permissions.
- Middleware verifies the user’s token, extracts their role, and ensures they have the required permissions for the requested action.

### **Error Handling**

**Error Responses:**

Define error responses for common failure scenarios.
```Example:``` If there are database issues, return a 500 status code with an error message.
```json
{
  "status": "unsuccessful",
  "status_code": 500,
  "message": "Failed to create blog post. Please try again later."
}
```

**Edge Cases:**

Consider edge cases such as empty title or content.
```Example:``` Handle scenarios where the database is temporarily unavailable.

### **Performance and Security**
**Performance Considerations:**

Review potential performance implications and optimize the API for efficiency.
```Example:``` Implement rate limiting to prevent abuse.

**Security Concerns:**

Address security considerations such as data sanitization.
```Example:``` Sanitize user inputs to prevent injection attacks.

### **Documentation**
**API Documentation:**

Ensure that API documentation is updated to include details about the new endpoint, request/response formats, error handling, and authentication requirements.

### **Technical Notes:**

Include any additional technical notes or considerations.

### **Testing Requirements**
**Unit Tests:**

Write unit tests to validate input data and blog post creation logic.

**Integration Tests:**

Ensure end-to-end functionality is tested with integration tests.

### **Dependencies and Impact**
**Dependencies:**

- User authentication system must be fully functional.
- Database schema must support the new blog post model.

### **Additional Information**

- Refer to the existing authentication middleware for user verification.

- Follow the current project structure and coding standards.

- Ensure the blog post creation feature integrates smoothly with the rest of the application.

### **Impact Analysis:**

Assess the potential impact on other features or components, ensuring that existing functionality is not disrupted.

**Comment by StarmannRassy** [comment]
Guys please say something waiting on my issue's approval or otherwise so I work on it if the need be. 🙏

**Comment by StarmannRassy** [comment]
@AdeGneus

**Comment by incredible-phoenix246** [comment]
How are you authorizing your user

**Comment by StarmannRassy** [comment]
How do you mean please is it not done by checking user roles or permissions to confirm authorization.    

Example:
When a user attempts to perform an action, their request includes an authorization token (e.g., JWT).
The middleware decodes this token to identify the user’s roles.
Based on the roles, the middleware either grants or denies access to the requested resource.

**Comment by AdeGneus** [comment]
@StarmannRassy the entity field should be in snake case. What @incredible-phoenix246 is asking for is how you implement the authorisation which is mostly done by a middleware. Update it and I'll approve

**Comment by AdeGneus** [comment]
You haven't implemented the changes

**Comment by StarmannRassy** [comment]
Done
