### ISSUE TITLE
[FEAT]: API Endpoint To Perform a Soft Delete on a User

### ISSUE THREAD

**Issue by CollinDex** [hngprojects/hng_boilerplate_expressjs#128]
### Description

Implement an API endpoint feature to perform a soft delete on a user. This feature allows marking a user as deleted without actually removing the user record from the database. The `deleted_at` timestamp and `is_deleted` property will be set when a user is soft deleted.

### Endpoint Feature

- This endpoint enables authenticated users to perform a soft delete.
- Only a SuperAdmin is allowed to permanently delete a user.

### Acceptance Criteria

- [x] The endpoint should be accessible at `DELETE /api/v1/users/:id`
- [x] The endpoint should accept `HTTP DELETE` requests.
- [x] Only authenticated users can perform a soft delete.
- [x] The user model is updated to include a `deleted_at` and `is_deleted` field.
- [x] When a user is soft deleted, the `deleted_at` field is set to the current timestamp and `is_deleted` is set to true.
- [x] Soft-deleted users should not appear in user queries. 
- [x] The endpoint should return a 202 status code with a success message on a successful soft delete.

## Request Example:
DELETE /api/v1/users/:id

## Response Example:
On successful soft delete of a User, the API should return a 202 status code.
```json
{
  "status":"success",
  "status_code": 202,
  "message": "User deleted successfully"
}
```

## Input Validation:

- Confirm that `id` is provided and valid.
- If `id` is invalid return a 400 status code with an error message.

```json
{
  "status":"unsuccessful",
  "status_code": 400,
  "message": "Valid id must be provided"
}
```

## Output Validation:

- Ensure the response format is correct and includes appropriate status codes and messages.
- If `id` is not found return a 404 status code with an error message.

```json
{
  "status":"unsuccessful",
  "status_code": 404,
  "message": "User not found."
}
```

- If there is an error in performing a soft delete the API should return a 500 Internal Server Error status code with an appropriate message:

```json
{
  "status":"unsuccessful",
  "status_code": 500,
  "message": "Failed to perform soft delete."
}
```

## Authentication
- Verify that the user is authenticated before allowing access to the endpoint.
- Example: Use middleware to check for a valid authentication token.

## Error Responses

- Define error responses for common failure scenarios.
- Example: If id is invalid, return a  400 status code with an error message

```json
{
  "status":"unsuccessful",
  "status_code": 400,
  "message": "Valid id must be provided"
}
```

## Edge Cases
- Consider edge cases such as no id provided.
- Example: Handle scenarios where the id is not provided.

## Performance Considerations
- Review potential performance implications and optimize the API for efficiency.

## Security Concerns

- Address security considerations such as data sanitization.

### API Documentation

- Ensure that API documentation is updated to include details about the new endpoint, request/response formats, error handling, and authentication requirements.

## Unit Tests

- Write unit tests to validate input data and soft delete sending logic.

## Integration Tests

- Ensure end-to-end functionality is tested with integration tests.

## Dependencies

- User authentication

## Impact Analysis

- Assess the potential impact on other features or components, ensuring that existing functionality is not disrupted.

**Comment by CollinDex** [comment]
@incredible-phoenix246  @AdeGneus

**Comment by AdeGneus** [comment]
Good issue. You can set an `is_deleted` boolean field along with the timestamp.

**Comment by CollinDex** [comment]
> Good issue. You can set an `is_deleted` boolean field along with the timestamp.

Thanks. Issue has been updated to set an `is_deleted` boolean field as requested.
