### ISSUE TITLE
[FEAT]: API Endpoint For SuperAdmin To Send Invite To A User To Join An Organisation

### ISSUE THREAD

**Issue by etanami** [hngprojects/hng_boilerplate_expressjs#135]
### Description
Implement an API endpoint feature that allows Super-Admin to send invitation to a particular user to join an organisation. This feature will enable admins to invite new members to their organisation via email.

### Acceptance Criteria

- [ ] The endpoint should be accessible at POST /api/v1/organizations/:orgId/invite
- [ ] The endpoint should accept HTTP POST requests.
- [ ] Only authenticated admins can send invitations.
- [ ] The request body should include the email address of the invitee.
- [ ] The endpoint should generate a unique invitation token and send an email to the invitee.
- [ ] The invitation token should be stored in the database with an expiration time.
- [ ] The endpoint should return a 201 OK status code with a success message on a successful invitation.

**Response**:
On successful invitation, the API should return a 201 OK status code.

```
{
  "status": "success",
  "status_code": 201,
  "message": "Invitation sent successfully"
}
```

### Data Validation
**Input Validation:**

- Confirm that email is provided and valid.
- If email is invalid, return a 400 status code with an error message.

```
{
  "status": "unsuccessful",
  "status_code": 400,
  "message": "Valid email must be provided"
}
```

**Output Validation:**

- Ensure the response format is correct and includes appropriate status codes and messages.
- If the organization ID is not found, return a 404 status code with an error message.

```
{
  "status": "unsuccessful",
  "status_code": 404,
  "message": "Organisation not found."
}

```
- If there is an error in sending the invitation, the API should return a 500 Internal Server Error status code with an appropriate message.

```
{
  "status": "unsuccessful",
  "status_code": 500,
  "message": "Failed to send invitation."
}
```

### Implementation Details:

- Implement middleware to check for authentication and authorization before allowing the invitation operation.
- Add tests to verify that only authenticated and authorized user(Superadmin) can send invites.

### Error Handling
**Error Responses:**

Define error responses for common failure scenarios.
Example: If email is invalid, return a 400 status code with an error message.

```
{
  "status": "unsuccessful",
  "status_code": 400,
  "message": "Valid email must be provided"
}
```

### Performance and Security
**Performance Considerations**
- Review potential performance implications and optimize the API for efficiency.
- Example: Implement rate limiting to prevent abuse.

### Testing Requirements
**Unit Tests**

Write unit tests to validate that only an authorized admin can send an invitation to a particular user.

**Comment by incredible-phoenix246** [comment]
How do you verify that the person sending is a super admin

**Comment by etanami** [comment]
Check if the user is a super admin first - using checkPermissions middleware

**Comment by incredible-phoenix246** [comment]
If the user is not an admin 

You didn't handle that in yr issue

**Comment by etanami** [comment]
ohh ohh. I missed that

I've added it now
