### ISSUE TITLE
API Endpoint for Getting All Organisation With Pagination(Super admin)

### ISSUE THREAD

**Issue by Shabzynana** [hngprojects/hng_boilerplate_expressjs#138]
## Description
Implement an API endpoint to retrieve all organisation with pagination. This endpoint allows authenticated super admins to perform this action.

## Acceptance Criteria

- Endpoint is protected.
- This endpoint enables authenticated super admins to retrieve a paginated list of all organisation.
- Limited to users with super admin privileges to maintain system security.

### Requirements	
- [ ] Authentication: This endpoint requires authentication.
   -  The authentication token (Bearer ey9hk3j4g...) must be sent in the request header as Authorisation.
- [ ] Access Control: Only super admins can access this endpoint.
- [ ]  The endpoint should support pagination .
- [ ]  The endpoint should return a paginated list of organisation with relevant details.
- [ ]  The endpoint should return a 200 OK status code with the list of organisation.

### [GE] /api/v1/organisations?page=1&limit=5&offset=0

*Get an organisation*
1. Endpoint Flow

- This endpoint get all organisation 

### Successful Response

*Status Code*: 200
*Description:* Success

```json
{
  "status": "success",
  "status_code": 200,
  "data": {
    "organisation": [
      {
         "name": "String",
         "description": "String",
         "email": "string",
         "industry": "string",
          "type": "string",
      .......
    ]
  }
}
```

### Error Response

*Status Code:* 404
*Description:* No organisation.
```json
{
    "success": false,
    "message": No organisation as been created
    "status_code": 404
}
```

*Status Code:* 500
*Description:* Internal Server error

```json
{
    "success": false,
    "message": Something went wrong, please try again later or contact support it persists,
    "status_code": 500
}
```

### Data Validation 

Input Validation:

- Confirm that a page, limit and offset are all positive numbers
- Example: If page or limit are invalid, return a 400 status code with an error message:

```json
{
  "status": "unsuccessful",
  "status_code": 400,
  "message": "Invalid pagination parameter"
}
```

### Authentication
-  Verify that the user is authenticated before allowing access to the endpoint.

### Authorization
- Ensure that only super admin users can access this endpoint.

## Error response 

*Status Code:* 403
*Description:* Forbidden, Only SuperAdmins can access this endpoint.
```json
{
    "success": false,
    "message": "Access denied. Super admin privileges required."
    "status_code": 403
}
```

## Dependencies
- This endpoint depends on the Database setup task, as it involves interaction with the database.
- Ensure the user authentication middleware up and running
- Role-Based Access Control must be set up to properly access this endpoint as only SuperAdmins can perform this action

**Comment by AdeGneus** [comment]
This is a good issue. I see that some of you with pagination want to enforce it on the backend. Fix the README
