### ISSUE TITLE
[FEAT]: API Endpoint to Make Payments Using FlutterWave

### ISSUE THREAD

**Issue by Uzo-Felix** [hngprojects/hng_boilerplate_expressjs#152]
## Implement Payment Functionality Using FlutterWave

## Description

Implement payment functionality using FlutterWave to allow both individual users and organizations to make payments through our platform. This feature would handle the entire payment process, including initiating the payment and processing it.

## Acceptance Criteria

- [ ] The API should be accessible at `POST /api/v1/payments/initiate`  
- [ ] Endpoint is accessible only to authenticated users.  
- [ ] Only users with appropriate permissions can initiate payments.  
- [ ] Sanitize and validate all input data to prevent injection attacks.  
- [ ] Data is transmitted over HTTPS, and sensitive information is handled securely.  
- [ ] Write unit and integration tests for the payments logic.  
- [ ] Provide clear and comprehensive documentation for the endpoint, including request and response formats, error codes, and usage examples.

#### Request Body:

```json
{
   "payer_type": "user" | "organization",  // Type of the payer (e.g., user or organization)
   "payer_id": "user@gmail.com",
   "amount": 49.99,
   "currency": "USD"
}
```

#### Response Body:

```json
{
   "payment_id": "abc_123",  // Unique identifier for the payment 
   "status": "pending", // Status of the payment (initial status)
   "payment_url": "https://example.com/checkout?paymentId=pay_abc123" // URL to complete the payment
}
```

##### Response Body:

```json
{
  "error": "Bad Request",
  "message": "Validation error: amount must be a positive number",
  "status_code": 400
}
```

##### Response Body:

```json
{
  "error": "Unauthorized",
  "message": "Authentication required",
  "status_code": 401
}
```

##### Response Body:

```json
{
  "error": "Forbidden",
  "message": "You do not have permission to initiate this payment",
  "status_code": 403
}
```

##### Response Body:

```json
{
  "error": "Internal Server Error",
  "message": "An unexpected error occurred. Please try again later.",
  "status_code": 500
}
```

### Input Validation:

Confirm that all fields are provided and valid.

#### Example:

If `payer_id` is invalid or missing, return a 400 status code with an error message.

```json
{
  "error": "Bad Request",
  "message": "Validation error: payer_id must be provided",
  "status_code": 400
}
```

### Authentication:

Verify that the user is authenticated before allowing access to the endpoint.

#### Example:

Use middleware to check for a valid authentication token.

### Authorization:

Ensure that only authorized users can make payments.

#### Example:

Check user roles or permissions to confirm authorization.

### Error Responses:

Define error responses for common failure scenarios.

#### Example:

If FlutterWave credentials are invalid, return a 500 status code with an error message.

```json
{
  "error": "Payment Initialization Failed",
  "message": "Failed to initialize payment with FlutterWave: Invalid API key",
  "status_code": 502
}
```

## API Documentation:

Ensure that API documentation is updated to include details about the new endpoint, request/response formats, error handling, and authentication requirements.

## Unit Tests:

  Implement unit tests covering:  
  - [ ] Input validation  
  - [ ] Authentication  
  - [ ] Authorization  
  - [ ] Payment logic

## Integration Tests:

Ensure end-to-end functionality is tested with integration tests.

**Comment by PreciousIfeaka** [comment]
Your request body says payer_id but your validation check uses user_id.
Outline what your unit tests will cover.
