### ISSUE TITLE
[FEAT] - Documentation for all User Endpoints

### ISSUE THREAD

**Issue by mahmudW** [hngprojects/hng_boilerplate_expressjs#167]
### Description

This document outlines the API endpoints related to User  for our application. These endpoints facilitate user registration, authentication, profile management, and related operations.

### Endpoints

Base Url: api/v1/user

1. Register User

- Method: POST
- Endpoint: /register
- Description: Register a new User
- Request Body:
`{
  "username": "string",
  "email": "string",
  "password": "string"
}
`
Success:

- code: 201 Created
-  Message:
`{
  "message": "User registered successfully"
}
`
Error: 
- code: 400 Bad Request
-  Message:
`{
  "error": "Validation error: Invalid email format"
}
`
2. Login User

- Method: POST
- Endpoint: /login
- Description: Authenticate a user and generate a JWT Token
- Request Body:
`{
  "email": "string",
  "password": "string"
}
`
Success:

- code: 200 Ok
-  Message Body:
`{
  "token": ""
}
`
Error: 
- code: 401 Unauthorized
-  Message Body:
`{
  "error": "Validation error"
}
`

3. Get All Users

- Method: GET
- Endpoint: /
- Description: Retrieve all users information
Success:

- code: 200 Ok
-  Message Body:
`{
  "username": "string",
  "email": "string",
  "password": "string"
}
`
Error: 
- code: 401 Unauthorized
-  Message Body:
`{
  "error": "unauthorized"
}
`

4. Get Specific User

- Method: GET
- Endpoint: /{user_id}
- Description: Get a specific user
- Parameter: user_id (required)
- Response Body:
`{
  "username": "string",
  "email": "string"
}
`
Error: 
- code: 401 Unauthorized
-  Message Body:
`{
  "error": "unauthorized"
}
`
- code: 404 Not found
-  Message Body:
`{
  "error": "User not found"
}
`

5. Update User profile

- Method: PUT
- Endpoint: /{user_id}
- Description: Update a user detail
- Parameter: user_id (required)
- Request Body:
`{
  "username": "string",
  "email": "string"
}
`
Success:
- code: 201 Created
-  Message:
`{
  "message": "Profile updated successfully"
}
`
Error: 
- code: 401 Unauthorized
-  Message Body:
`{
  "error": "unauthorized"
}
`

6. Delete a User

- Method: DELETE
- Endpoint: /users/{id}
- Description: Permanently delete the account of the authenticated user.
- Parameter: user_id (required)

Success:
- code: 201 Created
-  Message:
`{
  "message": "Profile updated successfully"
}
`
Error: 
- code: 401 Unauthorized
-  Message Body:
`{
  "error": "unauthorized"
}
`

### Authentication and Authorization

- Verify that the user is authenticated
- Ensure that only authorized users can retrieve, update and delete a user.

### API Documentation
Ensure that API documentation is updated to include details about the new endpoint, request/response formats, error handling, and authentication requirements.

### Testing Requirements

**Unit Tests** 
Write unit tests to validate input data and user logic.

**Integration Tests**
Ensure end-to-end functionality is tested with integration tests.

### Dependencies and Impact

**Dependencies**

- Identify dependencies on other tasks or systems, such as user authentication.

**Impact Analysis**

- Assess the potential impact on other features or components, ensuring that existing functionality is not disrupted.

**Comment by masterchief-Dave** [comment]
@mahmudW, @incredible-phoenix246,
There is an error in this documentation, in `get all users route` your response body cannot be an `object` it will be an `array of objects`. Aside that usually pagination comes with endpoints like this because if you have `1 million users` you will not want to query the database for `1 million users` at a time.

I don't mean to discredit your work @mahmudW but you did not take time to write this doc. properly. There are other things like, `delete a  user route` should be a protected route according to this documentation, it is a public route because it does not show it requires `Authorization header` in the request.

**Comment by mahmudW** [comment]
Corrections taken sure, bro.
Honestly, I borrowed a PC to come up with this... my PC got an issue. Right now, I don't have a PC at my disposal.
Thank you so much for identifying these issues. Even from the indentation, I felt I needed to edit it
